#!/bin/bash
# (C) 2014, Yann E. MORIN <yann.morin.1998@free.fr>
# License: at your option, either one of: GPLv2 or GPLv3,
# see LICENSE.GPLv2 and LICENSE.GPLv3 in this repository

main() {
    local base

    base="$( git describe --abbrev=0 )"

    git log "${@}" "${base}"..
}

main "${@}"
