#!/bin/bash
# (C) 2014, Yann E. MORIN <yann.morin.1998@free.fr>
# License: GPLv2, see LICENSE.GPLv2 in this repository

main() {
    local base

    base="$( git describe --abbrev=0 )"

    git log "${@}" "${base}"..
}

main "${@}"
