#!/bin/bash
# (C) 2014, Yann E. MORIN <yann.morin.1998@free.fr>
# License: GPLv2, see: http://www.gnu.org/licenses/old-licenses/gpl-2.0.html
set -e

main() {
    local -a remotes
    local -a branches
    local remote branch

    remotes=( $( git remote -v \
                 |awk '$(NF)=="(push)" && $(2)!="/dev/null" {print $(1);}'
               )
            )

    branches=( $( git branch |awk '{ print $(NF); }' ) )

    for remote in "${remotes[@]}"; do
        printf "Pushing branches to '%s'...\n" "${remote}"
        git push -f "${remote}" "${branches[@]}"
    done
}

main "${@}"
