#!/bin/bash
# (C) 2014, Yann E. MORIN <yann.morin.1998@free.fr>
# License: at your option, either one of: GPLv2 or GPLv3,
# see LICENSE.GPLv2 and LICENSE.GPLv3 in this repository

main() {
    local range

    range="$( LC_ALL=C git push -n "${@}" 2>&1                  \
              |tail -n +2                                       \
              |sed -r -e 's/^[[:space:]]*([^[:space:]]+).*/\1/' \
            )"
    if [ -n "${range}" ]; then
        git --no-pager log --oneline --decorate "${range}"
    else
        printf "Everything up-to-date\n" >&2
    fi
}

main "${@}"
